### ISSUE TITLE
PoC: Dependabot

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sebastian-sommerfeld-io/docker-image-adoc-antora#15]
- [x] Test dependabot
- [x] Check if pipeline is static or contains some project-specific steps
  - [x] If static, add to jarvis module "github-actions"
- [x] sebastian-sommerfeld-io/jarvis#53
- [x] sebastian-sommerfeld-io/docker-image-adoc-antora#19
- [x] sebastian-sommerfeld-io/docker-image-adoc-antora#20
- [x] sebastian-sommerfeld-io/jarvis#59
- [x] Update onboarding.adoc in config repo

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates

PoC in Repo
- https://github.com/sebastian-sommerfeld-io/docker-image-adoc-antora
- https://github.com/sebastian-sommerfeld-io/docker-image-folderslint

**Comment by sebastian-sommerfeld-io** [comment]
### New Settings with enabled Dependabot

![image](https://user-images.githubusercontent.com/101367275/206926170-24320df9-adbf-4d72-baed-88c6889af826.png)
